### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Portal2001** [ofunny/BedrockPlayerManager#1]
Please make this for bungee as I can't use it when I am managing a network

**Comment by ofunny** [comment]
It should work within a bungee network since I also use it like that.
What exactly does not work for you? (You just need to install it on each server, see the howto on https://www.spigotmc.org/resources/bedrock-player-managment-for-floodgate-geyser.82278/ )

**Comment by ofunny** [comment]
Closed because of inactivity and missing informations by the creator …
