### ISSUE TITLE
Not working on Floodgate 2.0.

### ISSUE THREAD

**Issue by notsatvrn** [ofunny/BedrockPlayerManager#2]
Console output:

```
>.... [17:09:06 ERROR]: [BedrockPlayerManager]: floodgate-bukkit plugin not found! Flootgate must be installed on your server for BedrockPlayerManager to work properly! Only the module 'commands.all' can work without Floodgate!
```
Floodgate's plugin name is now just `floodgate` instead of `floodgate-bukkit`

**Comment by Virologicbody** [comment]
Same issue for me.
Running Paper build 1.16.5-565
Geyser dev 2.0
Floodgate 2.0

**Comment by ofunny** [comment]
I'm working on an update today, to support the new Floodgate-API, check out https://discord.gg/7JvZdvaT7D to stay on track.

**Comment by ofunny** [comment]
New version including Floodgate 2.0 support has meanwhile been released: https://www.spigotmc.org/resources/bedrock-player-managment-for-floodgate-geyser.82278/
