### ISSUE TITLE
Error in Spigot/backend server when joined by Java player

### ISSUE THREAD

**Issue by Virologicbody** [ofunny/BedrockPlayerManager#3]
Running Paper 1.16.5-565
I'm using:
Geyser dev 2.0 on my proxy with Floodgate 2.0 with send-floodgate-data: true
Floodgate 2.0 on my Spigot/backend server and copied the key files from the proxy.

Error in console on backend server when a Java player joins:
[https://pastebin.com/ux1LLQnn](url)

**Comment by ofunny** [comment]
Duplicate of #2 
check out the answers there.
