### ISSUE TITLE
Floodgate not detected when using proxy version

### ISSUE THREAD

**Issue by srnyx** [ofunny/BedrockPlayerManager#6]
I'm using Floodgate/Geyser proxy edition and I have BedrockPlayerManager proxy edition (on the proxy) **and** Spigot edition (on backend), but the Spigot edition isn't detecting Floodgate.

```[22:35:08 WARN]: [BedrockPlayerManager]: neither Floodgate API version 1.x nor 2.x has been detected – plugin running in 'solo mode' without Floodgate, all players will be treated as Java players!```

**Comment by ofunny** [comment]
Did you install Floodgate on your Spigot servers as well and also turned on "send-floodgate-data" and ip forwarding on your proxy?

**Comment by srnyx** [comment]
> Did you install Floodgate on your Spigot servers as well and also turned on "send-floodgate-data" and ip forwarding on your proxy?

No. But I recently uninstalled FloodGate as I was informed it's considered piracy. You can probably close this issue.
